live_config_reload = true

[font]
size = 11.3

[font.normal]
family = "FiraCodeNerdFont"


[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[window]
opacity = 0.8

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0
