-- return {
--   {
--     'Shougo/ddu.vim',
--     cmd = { 'Ddu' },
--     dependencies = {
--       'vim-denops/denops.vim',
--       'nvim-tree/nvim-web-devicons',
--       -- UI
--       'Shougo/ddu-ui-ff',
--       -- Kinds
--       'Shougo/ddu-kind-file',
--       -- Filters, Sorters, Columns
--       'Shougo/ddu-filter-matcher_fido',
--       'Shougo/ddu-sorter-filename',
--       'kyoh86/ddu-column-git',
--       -- Sources
--       'Shougo/ddu-source-file', -- Provides 'file' and 'oldfile' sources
--       'Shougo/ddu-source-file_rec',
--       'Shougo/ddu-source-rg',
--       'Shougo/ddu-source-buffer',
--       'Shougo/ddu-source-help',
--       'yuki-yano/ddu-source-nvim-notify',
--     },
--     config = function()
--       local ddu_custom = vim.fn['ddu#custom#patch_global']
--
--       ddu_custom({
--         ui = 'ff',
--         uiParams = {
--           ff = {
--             split = 'floating',
--             winWidth = 120,
--             winRow = 25,
--             autoResize = true,
--             previewEnabled = true,
--             previewWidth = 80,
--             previewHeight = 25,
--             keymap = {
--               ['<CR>'] = '<Cmd>call ddu#ui#do_action("itemAction")<CR>',
--               ['p'] = '<Cmd>call ddu#ui#do_action("togglePreview")<CR>',
--               ['i'] = '<Cmd>call ddu#ui#open_filter_window()<CR>',
--               ['q'] = '<Cmd>call ddu#ui#quit()<CR>',
--               ['<ESC>'] = '<Cmd>call ddu#ui#quit()<CR>',
--             },
--           },
--         },
--         sourceOptions = {
--           _ = {
--             matchers = { 'matcher_fido' },
--             converters = { 'nvim-web-devicons' },
--             columns = { 'git' },
--           },
--           file_rec = {
--             sorters = { 'sorter_filename' },
--           },
--           rg = {
--             params = {
--               args = { '--column', '--no-heading', '--color', 'never' },
--             },
--           },
--         },
--         kindOptions = {
--           file = { defaultAction = 'open' },
--           help = { defaultAction = 'open' },
--           buffer = { defaultAction = 'open' },
--         },
--       })
--
--       -- Global keymaps to launch DDU
--       local keymap = vim.keymap.set
--       local ddu_start = function(opts)
--         vim.fn['ddu#start'](opts)
--       end
--
--       keymap('n', 'ff', function() ddu_start({ sources = { { name = 'file_rec' } } }) end, { desc = '[F]ind [F]iles (DDU)' })
--       keymap('n', 'fg', function()
--         local input = vim.fn.input('Grep > ')
--         if input ~= '' then
--           ddu_start({ sources = { { name = 'rg', params = { input = input } } } })
--         end
--       end, { desc = '[F]ind by [G]rep (DDU)' })
--       keymap('n', 'fb', function() ddu_start({ sources = { { name = 'buffer' } } }) end, { desc = '[F]ind [B]uffers (DDU)' })
--       keymap('n', 'fr', function() ddu_start({ sources = { { name = 'oldfile' } } }) end, { desc = '[F]ind [R]ecent (DDU)' })
--       keymap('n', 'fh', function() ddu_start({ sources = { { name = 'help' } } }) end, { desc = '[F]ind [H]elp (DDU)' })
--       keymap('n', 'fn', function() ddu_start({ sources = { { name = 'notify' } } }) end, { desc = '[F]ind [N]otify (DDU)' })
--     end,
--   },
-- }
return {}
